### ISSUE TITLE
a problem with validation

### ISSUE THREAD

**Issue by samixp02** [nkovacs/yii2-datetimepicker#2]
i need to know where to add this line exactly 
\nkovacs\datetimepicker\DateTimeValidator::register();

this is my config file of backend

`<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-backend',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'backend\controllers',
    'bootstrap' => ['log'],
    'modules' => [],
    'components' => [
        'request' => [
            'csrfParam' => '_csrf-backend',
        ],
        'user' => [
            /*'identityClass' => 'common\models\User',*/
            //'enableAutoLogin' => true,
            'identityCookie' => ['name' => '_identity-backend', 'httpOnly' => true],
            'class' => 'webvimark\modules\UserManagement\components\UserConfig',

        // Comment this if you don't want to record user logins
        'on afterLogin' => function($event) {
                \webvimark\modules\UserManagement\models\UserVisitLog::newVisitor($event->identity->id);
            }
        ],
        'session' => [
            // this is the name of the session cookie used for login on the backend
            'name' => 'advanced-backend',
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        /*
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
            ],
        ],
        */
    ],
    'params' => $params,
];
`

**Comment by nkovacs** [comment]
Put it before the return.

**Comment by samixp02** [comment]
doesn't save the datetime to the database  0000-00-00 00:00:00

**Comment by nkovacs** [comment]
If you want to save it into a database, you must use [timestampAttribute](http://www.yiiframework.com/doc-2.0/yii-validators-datevalidator.html#$timestampAttribute-detail) (and possibly [timestampAttributeFormat](http://www.yiiframework.com/doc-2.0/yii-validators-datevalidator.html#$timestampAttributeFormat-detail)) to convert the value into something your database can understand.

**Comment by samixp02** [comment]
the problem was in the format  it will be great if the format was like that `yyyy-mm-dd hh:ii:ss`

**Comment by nkovacs** [comment]
The format is dependent on the current locale, so you can't insert that into the database. That's why timestampAttribute exists, it allows you to get a parsed value that your database will understand.

**Comment by samixp02** [comment]
so i need to use it in the rules right?

**Comment by nkovacs** [comment]
Here's one solution that uses a different attribute to store the parsed value, and overwrites the original in beforeSave: http://www.yiiframework.com/forum/index.php/topic/66303-datepicker-and-datevalidator-format-dont-working-solved/page__view__findpost__p__286175

**Comment by samixp02** [comment]
here is my model file
`<?php

namespace app\models;
use Yii;
/**
 * This is the model class for table "event".
 *
 * @property integer $id
 * @property string $title
 * @property string $start
 * @property string $end
 * @property integer $user_id
 */
class Event extends \yii\db\ActiveRecord
{
    public $date_start;
    public $date_end;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event';
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
        [['title', 'start', 'end', 'user_id'], 'required'],
            //[['start', 'end'], 'safe'],
            [['start'], 'datetime', 'timestampAttribute' => '$date_start'],
            [['end'], 'datetime', 'timestampAttribute' => '$date_end'],
            [['user_id'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['description'], 'string', 'max' => 255],
        ];
    }
 public function beforeSave($insert)
    {
       if (parent::beforeSave($insert)) {

        $this->start = Yii::$app->formatter->asDate($this->date_start, 'MM/dd/yyyy HH:mm:ss');
        $this->end = Yii::$app->formatter->asDate($this->date_end, 'MM/dd/yyyy HH:mm:ss');

        return true;} else {
        return false;
    }
    }

    public function afterFind()
    {
        parent::afterFind();

        $this->start = Yii::$app->formatter->asDate($this->start, Yii::$app->formatter->datetimeFormat);
        $this->end = Yii::$app->formatter->asDate($this->end, Yii::$app->formatter->datetimeFormat);
        return true;
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'start' => 'Start',
            'end' => 'End',
            'description' => 'Description',
            'user_id' => 'User ID',
        ];
    }
}

`

**Comment by samixp02** [comment]
now it gives me" Creating default object from empty value"
`
 public function beforeSave($insert)
    {
       if (parent::beforeSave($insert)) {
          //signaled here
        $model->start = Yii::$app->formatter->asDate($_POST['Event']['start'], 'yyyy-MM-dd HH:mm:ss');
        $model->end = Yii::$app->formatter->asDate($_POST['Event']['end'], 'yyyy-MM-dd HH:mm:ss');

        return true;} else {
        return false;
    }
    }

    public function afterFind()
    {
        parent::afterFind();

        $this->start = Yii::$app->formatter->asDate($this->start, Yii::$app->formatter->datetimeFormat);
        $this->end = Yii::$app->formatter->asDate($this->end, Yii::$app->formatter->datetimeFormat);
        return true;
    }
`

**Comment by nkovacs** [comment]
Because it's not `$model`, it's `$this`.

**Comment by samixp02** [comment]
solved
