### ISSUE TITLE
Input not hidden when using inline mode

### ISSUE THREAD

**Issue by mmalisz** [nkovacs/yii2-datetimepicker#4]
The input from active field is shown when setting inline to true. Moreover, when focusing on the field, then losing it, the widget will be destroyed.

**Comment by nkovacs** [comment]
I've tried to implement this, but it looks broken with side-by-side:

![screenshot from 2017-03-28 10-23-37](https://cloud.githubusercontent.com/assets/2269242/24395722/ddb77b84-13a0-11e7-8319-6b6928d7c9dc.png)

The AM/PM toggle also looks wrong in dropdown mode with side-by-side, so maybe it's just a bug with the side-by-side mode in the js plugin (I'm using an older fork).

**Comment by mmalisz** [comment]
Well, it seems it might be your containers css issue. Look like this in my case:
![przechwycenie obrazu ekranu - 28 03 2017 - 10 44 18](https://cloud.githubusercontent.com/assets/1454016/24396455/9071abe4-13a3-11e7-9352-1f4c968831de.png)

**Comment by nkovacs** [comment]
You don't have seconds. Maybe that also affects it. 
This patch fixes it in dropdown mode, but not inline mode: https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1612

**Comment by mmalisz** [comment]
Ah, that's true. Adding seconds to the format causes this issue here as well.

**Comment by nkovacs** [comment]
I'll release a fix in my forked bootstrap js plugin.

**Comment by mmalisz** [comment]
Guess we can close it, as the AM/PM issue is not related to this plugin.

**Comment by nkovacs** [comment]
I've published releases of both packages. Can you test please?

**Comment by mmalisz** [comment]
I've added "bower-asset/nkovacs-bootstrap-datetimepicker" to my main composer file.
![przechwycenie obrazu ekranu - 28 03 2017 - 11 12 34](https://cloud.githubusercontent.com/assets/1454016/24397773/8abb91ac-13a7-11e7-8f26-b368b531b4b2.png)

**Comment by nkovacs** [comment]
You don't have to add it directly, you just need to run composer update.

**Comment by mmalisz** [comment]
Ah, sorry, I've only updated yii2-datetimepicker package.
Now it seems to look alright.
