### ISSUE TITLE
Datetimepicker with sideBySide option is not displayed properly

### ISSUE THREAD

**Issue by re1naldo** [nkovacs/yii2-datetimepicker#5]
Code:
```
$form->field($model, 'date', [
    'template' => '<div class="row"><div class="col-xs-11 col-md-3">{label}{input}{error}</div></div>'
])->widget(DateTimePicker::classname(), [
    'format' => 'php:m/d/Y h:i A',
    'sideBySide' => true,
    'clientOptions' => [
        'allowInputToggle' => true,            
        'stepping' => 30
    ],
);
```

Result:
![](http://rei-lab.space/datetimepicker.png?raw=true)

How to display datetimepicker with sideBySide option?

**Comment by nkovacs** [comment]
Looks like another bug in the js plugin. It doesn't add the `wider` css class if you use a 24h format.

**Comment by nkovacs** [comment]
It was a bug in the js plugin. Fixed it, please run composer update and make sure bower-asset/nkovacs-bootstrap-datetimepicker is updated to 5.0.4.
