### ISSUE TITLE
Uncaught TypeError: Cannot read property 'minDate' of undefined

### ISSUE THREAD

**Issue by Aplear** [nkovacs/yii2-datetimepicker#6]
Hi! I can't set min date to another datetimepicker, how can I fix this? Thank's
'clientEvents' => [
                'dp.change' => "function(e){
                  $('#end_at').data('DateTimePicker').minDate(e.date);                 
                }"
            ]

**Comment by nkovacs** [comment]
`$('#end_at').data('DateTimePicker')` is undefined. Are you sure you're selecting the correct element?

**Comment by ashwiniboju** [comment]
$('#pp_iss_dt').data("DateTimePicker").maxDate(e.date); its working in english version but not working i use locale:'ar' how fix this can anyone help me please.
